client_config_backend: settings
client_config:
  client_id: 927503400803-vq5fmoimn2o7j8665r5hhnhmljeh5f72.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: pygmulib_creds.txt

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive

client_config_file: client_secrets.json
